### ISSUE TITLE
Domain Kurulduktan Sonra Sudoers'e Domain Admins Eklenmesi

### ISSUE THREAD

**Issue by duygupotur** [aciklab/samba#5]
Domain kurulduktan sonra aşağıdaki dosya oluşturulmalı

/etc/sudoers.d/domainadmins 

Dosya içerisine aşağıdaki bilgiler eklenmeli

```
%domain\x20admins ALL=(ALL) ALL

**Comment by zekiahmetbayar** [comment]
Son commit ile çözülmüştür.
